db.City.insert({CityZipCode: "6400", CityName: "Soenderborg"})
db.City.insert({CityZipCode: "7400", CityName: "Herning"})
db.City.insert({CityZipCode: "7430", CityName: "Ikast"})
db.City.insert({CityZipCode: "8000", CityName: "Aarhus C"})
db.City.insert({CityZipCode: "8100", CityName: "Aarhus C"})
db.City.insert({CityZipCode: "8200", CityName: "Aarhus N"})
db.City.insert({CityZipCode: "8210", CityName: "Aarhus V"})
db.City.insert({CityZipCode: "8260", CityName: "Viby J"})
db.City.insert({CityZipCode: "8600", CityName: "Silkeborg"})
db.City.insert({CityZipCode: "9000", CityName: "Aalborg"})
db.City.insert({CityZipCode: "9900", CityName: "Frederikshavn"})